# Generated by Django 2.0 on 2018-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('id', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Salesorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('online', 'online payment'), ('COD', 'cash on delivery')], max_length=6)),
                ('name', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=None, to='app1.Customer')),
                ('product', models.ManyToManyField(to='app1.Product')),
            ],
            options={
                'db_table': 'salesorders',
            },
        ),
    ]
